### ISSUE TITLE
Getting Inkdrop to work on ArchLinux + KDE

### ISSUE THREAD

**Issue by ironmike-au** [inkdropapp/forum#45]
Hi there,

I'm migrating from macOS to KDE on Archlinux and Inkdrop is a must-have app for me, but I can't seem to get it working successfully on KDE. 

I am able to get it to open up successfully, but when trying to log in it is returning the following:
```
Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
  app:error failed to log in: +7s Error: Failed to store user ID to keychain.
    at e.set (/usr/share/inkdrop/resources/app.asar/main.js:6:22409)
    at e.<anonymous> (/usr/share/inkdrop/resources/app.asar/main.js:6:16502)
    at tryCatch (/usr/share/inkdrop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/share/inkdrop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/share/inkdrop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:95:21)
    at r (/usr/share/inkdrop/resources/app.asar/main.js:1:25796)
    at /usr/share/inkdrop/resources/app.asar/main.js:1:25908
    at process._tickCallback (internal/process/next_tick.js:103:7)
  Rollbar:log Successful api response. Link: https://rollbar.com/occurrence/uuid/?uuid=6b0ba964f71e462ea1d2ae21ba533f50 +9s
```

I'm sure that this is not a supported platform, so I understand if you are unable to help. But, I thought I would ask if you had any advice on how I might be able to fix this? 

Thanks,
Mike

**Comment by ironmike-au** [comment]
Sorry! I was too hasty to open a ticket. I was able to fix this by installing `gnome-keyring`. I now have Inkdrop working and it's great :)

Thanks!

**Comment by craftzdog** [comment]
Hi Mike,

Glad to hear that it worked on ArchLinux + KDE, great! 😄
Cheers
