### ISSUE TITLE
Clicking notebook in the sidebar appends unwanted filters in the search field

### ISSUE THREAD

**Issue by Jawabiscuit** [inkdropapp/forum#54]
## Bug report

After a fresh install, I made a brand new notebook called Python. I noticed clicking "First Notebook" back to "Python" I am seeing `-status:completed -status:dropped` being appended to the filter in the search box. It is either a bug or it isn't very obvious why this happens. I had these errors in the console however I think they are unrelated due to the fact that I cleared the console and failed to reproduce them.

`C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:284 Uncaught (in promise) Error: missing
    at C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:284:16
    at metaToPlainObject (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:288:5)
    at metaToValue (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:230:14)
    at metaToValue (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:222:22)
    at EventEmitter.<anonymous> (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:299:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

`Save error: Error: Document update conflict
    at C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:284:16
    at metaToPlainObject (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:288:5)
    at metaToValue (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:230:14)
    at metaToValue (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:222:22)
    at EventEmitter.<anonymous> (C:\Users\Jonas\AppData\Local\inkdrop\app-3.6.1\resources\electron.asar\renderer\api\remote.js:299:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

### Info
- Platform: Windows
- Platform version: 10
- App Version: 3.6.1

### Reproduce

1. Fresh install
2. Create note (also might be helpful to assign a status and possibly a tag)
3. Create new notebook
4. Drag note into new notebook (I tried right click menu as well)
5. Attempt to view notebook
6. Clicking on "First Notebook" should append `-status:completed -status:dropped` to the filter string in the search box
7. Clicking on the new notebook should do the same
8. deleting `-status:completed -status:dropped` in the search box and clicking on the notebook should re-append the string

**Comment by craftzdog** [comment]
Hi J. Thank you for reporting.
These errors aren't related to this issue, and this behavior is by design. Notes with completed and dropped status aren't shown by default.
Please see this documentation for more detail about searching: https://doc.inkdrop.info/manual/searching-notes
