### ISSUE TITLE
Linux app crashes on startup

### ISSUE THREAD

**Issue by parkerd** [inkdropapp/forum#59]
## Bug report

Linux app crashes on startup. Tried both the zip and deb downloads, same error.

```
  app:error Failed to init app: TypeError: Cannot read property 'addError' of null
  at e.exports.e.notifyFailure (/usr/lib/inkdrop/resources/app.asar/main.js:1:152433)
  at e.exports.e.observeUserConfig (/usr/lib/inkdrop/resources/app.asar/main.js:1:151874)
  at e.exports.e.load (/usr/lib/inkdrop/resources/app.asar/main.js:1:150517)
  at t.<anonymous> (/usr/lib/inkdrop/resources/app.asar/main.js:1:19460)
  at tryCatch (/usr/lib/inkdrop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:63:40)
  at Generator.invoke [as _invoke] (/usr/lib/inkdrop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:337:22)
  at Generator.prototype.(anonymous function) [as next] (/usr/lib/inkdrop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:96:21)
  at r (/usr/lib/inkdrop/resources/app.asar/main.js:1:1033)
  at /usr/lib/inkdrop/resources/app.asar/main.js:1:1181
  at t (/usr/lib/inkdrop/resources/app.asar/main.js:1:9205)
  at t.<anonymous> (/usr/lib/inkdrop/resources/app.asar/main.js:1:975)
  at t.e (/usr/lib/inkdrop/resources/app.asar/main.js:1:18890)
  at App.<anonymous> (/usr/lib/inkdrop/resources/app.asar/main.js:1:33743)
  at emitTwo (events.js:111:20)
  at App.emit (events.js:191:7)
 +0ms
  Rollbar:error Could not parse api response, err: SyntaxError: Unexpected token < in JSON at position 0 +0ms
```

### Info
- Platform: Ubuntu
- Platform version: 16.04
- App Version: 3.7.1

### Reproduce

1. Download
2. Install or unzip
3. Run `inkdrop`

**Comment by craftzdog** [comment]
Hi, thank you for reporting it.

That's weird, it looks like it's launching normally in my environment (Ubuntu 16.04).
Did you get same error on older version?
I'll look into it.

**Comment by craftzdog** [comment]
Seems like it fails to perform `observeUserConfig`.
Could you make sure if you have permissions to the config path `~/.config/inkdrop/config.cson`?

**Comment by parkerd** [comment]
I was able to run it under another account successfully, although in that case it did complain about the config path because the user had no `~/.config`. Came back to my account and ran with strace, the last error before the stacktrace is:

```
inotify_add_watch(33, "/home/pdebardelaben/.config/inkdrop/config.cson", IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF) = -1 ENOSPC (No space left on device)
```

Based on some similar examples I found, it appears that I was out of watches. Increasing `fs.inotify.max_user_watches` did the trick.

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by craftzdog** [comment]
Good to hear that!
